---
linux_roles:
  - flatpak
  - flameshot
  - geerlingguy.docker
  - fish
  - zsh
  - kitty
  - rsync
  - obsidian
  - wezterm
  - vivaldi
  - bitwarden

become_roles:
  - geerlingguy.docker
  - flatpak
  - fish
  - zsh
