---
- name: Add fish repository with key
  ansible.builtin.deb822_repository:
    name: fish-obs
    types: deb
    uris: "{{ fish_apt_repo_url }}"
    suites: "{{ fish_obs_suite }}"
    components: []
    signed_by: "{{ fish_apt_key_url }}"
    state: present
  become: true

- name: Install fish
  ansible.builtin.apt:
    update_cache: true
    name: "{{ fish_package }}{% if fish_version != 'latest' %}={{ fish_version }}{% endif %}"
    state: present
    allow_downgrade: "{{ fish_version != 'latest' }}"
  become: true
