---
- name: Add fish PPA (deb822)
  ansible.builtin.deb822_repository:
    name: fish-ppa
    types: deb
    uris: "{{ fish_apt_repo_url }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: "{{ fish_apt_key_url }}"
    state: present
  become: true

- name: Install fish
  ansible.builtin.apt:
    name: "{{ fish_package }}{% if fish_version != 'latest' %}={{ fish_version }}{% endif %}"
    state: present
    update_cache: true
    allow_downgrade: "{{ fish_version != 'latest' }}"
  become: true
