#!/bin/bash
# run_after_20-provision.sh
# Main provisioning script: mise install, ansible inventory generation, ansible playbook

set -euo pipefail

echo "=== Starting Provisioning ==="

# --- Determine paths ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ANSIBLE_DIR="$PROJECT_ROOT/ansible"

# --- Export mise to PATH ---
export PATH="$HOME/.local/bin:$PATH"

# --- Run mise install ---
if command -v mise &>/dev/null; then
    echo "Running mise install..."
    mise install
    echo "mise install complete"
else
    echo "Warning: mise not found, skipping mise install"
fi

# --- Generate Ansible inventory from chezmoi data ---
echo "Generating Ansible inventory..."

CHEZMOI_DATA=$(chezmoi data --format=json)
CATEGORY=$(echo "$CHEZMOI_DATA" | jq -r '.data.category // "[]"')
FORM_FACTOR=$(echo "$CHEZMOI_DATA" | jq -r '.data.form_factor // "unknown"')

# Detect WSL
IS_WSL=false
if [ -f /proc/version ] && grep -qi microsoft /proc/version; then
    IS_WSL=true
fi

# Generate inventory.yaml
cat > "$ANSIBLE_DIR/inventory.yaml" <<EOF
# Auto-generated by chezmoi — do not edit manually
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

all:
  children:
EOF

# Add category groups (multi-choice)
echo "$CATEGORY" | jq -r '.[]' | while read -r cat; do
    cat >> "$ANSIBLE_DIR/inventory.yaml" <<EOF
    ${cat}:
      hosts:
        localhost:
EOF
done

# Add form factor group
cat >> "$ANSIBLE_DIR/inventory.yaml" <<EOF
    ${FORM_FACTOR}:
      hosts:
        localhost:
EOF

# Add WSL group if applicable
if [ "$IS_WSL" = true ]; then
    WINDOWS_IP=$(ip route | grep default | awk '{print $3}')
    cat >> "$ANSIBLE_DIR/inventory.yaml" <<EOF
    wsl:
      hosts:
        localhost:
    windows_native:
      hosts:
        ${WINDOWS_IP}:
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_user: "{{ lookup('env', 'USER') }}"
EOF
    echo "Added WSL + Windows host ($WINDOWS_IP) to inventory"
fi

echo "Inventory generated at: $ANSIBLE_DIR/inventory.yaml"

# --- Run Ansible playbook (Linux/WSL only) ---
if [ "$(chezmoi data --format=json | jq -r '.chezmoi.os')" = "linux" ]; then
    if command -v ansible-playbook &>/dev/null; then
        echo "Running Ansible playbook..."
        
        # Pass chezmoi data as extra vars
        echo "$CHEZMOI_DATA" | jq '.data // {}' > /tmp/chezmoi-data.json
        
        ansible-playbook \
            -i "$ANSIBLE_DIR/inventory.yaml" \
            -e @/tmp/chezmoi-data.json \
            "$ANSIBLE_DIR/main.yaml"
        
        echo "Ansible playbook complete"
        
        # Clean up temp file
        rm -f /tmp/chezmoi-data.json
    else
        echo "Warning: ansible-playbook not found, skipping Ansible run"
    fi
else
    echo "Skipping Ansible (not on Linux)"
fi

# --- Run WinGet DSC (Windows Native only) ---
if [ "$(chezmoi data --format=json | jq -r '.chezmoi.os')" = "windows" ]; then
    echo "Running WinGet DSC configuration..."
    if command -v winget &>/dev/null; then
        winget configure "$PROJECT_ROOT/chezmoi/dot_config/winget.dsc.yaml"
        echo "WinGet DSC complete"
    else
        echo "Warning: winget not found, skipping WinGet DSC"
    fi
fi

echo "=== Provisioning Complete ==="
