---
- name: Add rsync PPA (deb822)
  ansible.builtin.deb822_repository:
    name: rsync-ppa
    types: deb
    uris: "{{ rsync_apt_repo_url }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: "{{ rsync_apt_key_url }}"
    state: present
  become: true

- name: Install rsync
  ansible.builtin.apt:
    name: "{{ rsync_package }}"
    state: present
    update_cache: true
  become: true
