# Main Ansible playbook
# Entry point for system-wide configuration
# pre_tasks dynamically group hosts by OS facts

- hosts: all
  gather_facts: yes
  become_method: sudo

  pre_tasks:
    # i.e. Debian, Windows, Darwin, etc.
    - name: Display OS family
      ansible.builtin.debug:
        var: ansible_facts['os_family']

    - name: Group by OS family
      ansible.builtin.group_by:
        key: "{{ ansible_facts['os_family'] | lower }}"

    # i.e. Pop!_OS, Ubuntu, Debian, Microsoft Windows 11 Pro, etc.
    - name: Display distribution
      ansible.builtin.debug:
        var: ansible_facts['distribution']

    - name: Group by distribution
      ansible.builtin.group_by:
        key: "{{ ansible_facts['distribution'] | lower }}"

    # i.e. Linux, Win32NT
    - name: Display system
      ansible.builtin.debug:
        var: ansible_facts['system']

    - name: Group by system
      ansible.builtin.group_by:
        key: "{{ ansible_facts['system'] | lower }}"

  tasks:
    - name: Process global roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ all_roles }}"

- hosts: all
  tasks:
    - name: Process All specific roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ all_roles }}"

- hosts: linux
  tasks:
    - name: Process Linux specific roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ linux_roles }}"

- hosts: windows
  tasks:
    - name: Process Windows specific roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ windows_roles }}"

- hosts: personal
  tasks:
    - name: Process Personal specific roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ personal_roles }}"

- hosts: gaming
  tasks:
    - name: Process Gaming specific roles
      ansible.builtin.include_tasks: tasks/run_group_roles.yaml
      vars:
        current_group_roles: "{{ gaming_roles }}"
