---
fish_apt_repo_url: http://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_13/
fish_apt_key_url: https://download.opensuse.org/repositories/shells:fish:release:4/Debian_13/Release.key
fish_obs_gpg_key_path: /etc/apt/keyrings/fish-obs.asc
fish_obs_suite: /
fish_package: fish
